### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by drey0143143** [clowdhaus/terraform-composite-actions#10]
I'm getting this message when i use action "clowdhaus/terraform-composite-actions/directories@v1.3.0"

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout

**Comment by bryantbiggs** [comment]
I don't believe this is related to the actions here since these are composite actions and they do not specify the runner's runtime version
